env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GDK_BACKEND,wayland

source = ~/.config/hypr/colors.conf

monitor=,preferred,auto,1

exec-once = waypaper --restore
#exec-once = waybar
exec-once = dunst
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = pactl set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo
exec-once = blueman-applet
exec-once = nm-applet
exec-once = systemctl --user start pipewire pipewire-pulse wireplumber
exec-once = /home/sevro/.config/eww/start_cava.sh
exec-once = quickshell

input {
    kb_layout = es
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
}

general {
    gaps_in = 4
    gaps_out = 10
    border_size = 2
    col.active_border = $color_primary $color_secondary 45deg
    col.inactive_border = $color_bg
    layout = dwindle
}

decoration {
    rounding = 6
    active_opacity = 0.92
    inactive_opacity = 0.80
    blur {
        enabled = yes
        size = 6
        passes = 3
    }
}

animations {
    enabled = yes
    bezier = gothic, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 6, gothic
    animation = windowsOut, 1, 5, default, popin 80%
    animation = fade, 1, 8, default
    animation = workspaces, 1, 5, gothic, slidevert
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
}

plugin {
    csgo-vulkan-fix {
        fix_mouse = true
        vkfix-app = cs2, 1440, 1080
    }
}


$mod = SUPER

bind = $mod, Return, exec, kitty
bind = $mod, Q, killactive
bind = $mod, Space, exec, rofi -show drun
bind = $mod, F, fullscreen
bind = $mod SHIFT, Q, exit
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = , Print, exec, grim ~/Pictures/captura-$(date +%s).png
bind = $mod, L, exec, hyprlock
bind = $mod, E, exec, thunar
bind = $mod, Z, exec, ~/.config/hypr/scripts/cava.sh
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, down, movewindow, d
bindel = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bindel = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindel = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = $mod, W, exec, waypaper
bind = $mod SHIFT, E, exec, wlogout
bind = $mod, B, exec, foliate  # B de Books
