background #080808
foreground #cccccc
selection_background #cccccc
selection_foreground #080808
cursor #cccccc
cursor_text_color #080808
color0  #080808
color1  #cccccc
color2  #888888
color3  #ffffff
color4  #444444
color5  #888888
color6  #ffffff
color7  #cccccc
color8  #333333
color15 #ffffff
